### ISSUE TITLE
Photos Webapp only displays "an error occured"

### ISSUE THREAD

**Issue by hamsdac** [nextcloud/photos#3040]
**Describe the bug**
When opening the Photos Webapp (http://LOCAL_NETWORK_IP:PORT/app/photos/) the following subpages display only "an error occured":
* all media
* photos
* videos
* favourites
* on this day

I only see the german errors and tabs, bear with me if I translated something wrong.
Yes, I am accessing via HTTP, not HTTPS, as this nextcloud instance is only reachable via local network.
Nextcloud is deployed via docker compose (running `image: nextcloud:31`).
The Photos app on Android, connected to this instance and user, displays my photos.

This is the `docker-compose.yaml` file:
```
x-default-service: &default-service
  restart: unless-stopped

x-default-service-with-env: &default-service-with-env
  <<: *default-service
  env_file:
    - .env

services:
  nextcloud:
    <<: *default-service-with-env
    container_name: nextcloud-app-${CI_ENVIRONMENT_NAME}
    hostname: nextcloud
    image: nextcloud:31
    depends_on:
      - redis
      - db
    volumes:
      - "${DEPLOY_DATA_FOLDER}/data/nextcloud:/var/www/html"
    ports:
      - "${WEB_BIND_IP}:${WEB_PORT}:80"
    environment:
      MYSQL_HOST: db
      NEXTCLOUD_ADMIN_USER: "${NEXTCLOUD_ADMIN_USER}"
      NEXTCLOUD_ADMIN_PASSWORD: "${NEXTCLOUD_ADMIN_PASSWORD}"

  db:
    <<: *default-service-with-env
    container_name: nextcloud-db-${CI_ENVIRONMENT_NAME}
    hostname: mariadb
    image: mariadb:11.4
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - "${DEPLOY_DATA_FOLDER}/data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    <<: *default-service
    container_name: nextcloud-redis-${CI_ENVIRONMENT_NAME}
    hostname: redis
    image: redis
```

**To Reproduce**
1. Go to 'photos' Webapp
2. Click on any of "all media", "photos", "videos", "favourites", "on this day"
3. See error

**Expected behavior**
The photos app should show my photos and videos.

**Screenshots**
Browser with console open.

![Image](https://github.com/user-attachments/assets/6cc662f2-b5b6-4134-a802-7ad0359ec8b2)

**Desktop (please complete the following information):**
 - OS: Fedora 42 Workstation
 - Browser Firefox 138.0.4 / Chromium 136.0.7103.113

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7a
 - OS: Android 14
 - Browser Stock Android Browser

**Browser log**
```
Failed to get subsystem status for purpose 
Object { rejected: true, message: Error }
content-script.js:104:25
[INFO] activity: Activity API registered 
Object { app: "activity", uid: "christoph", level: 1 }
logger-ByCR-oAD.chunk.mjs:4:296
[WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config 
Object { app: "viewer", uid: "christoph", level: 1, ignoredMimes: (4) […] }
logger-CSHmak5d.chunk.mjs:5:366
OCA.Files.Sidebar initialized files-sidebar.js:1:56991
OCA.Comments.View initialized comments-comments-app.js:1:16945
OCA.Sharing.ShareSearch initialized files_sharing-files_sharing_tab.js:1:680
OCA.Sharing.ExternalLinkActions initialized files_sharing-files_sharing_tab.js:1:1468
OCA.Sharing.ExternalShareActions initialized files_sharing-files_sharing_tab.js:1:2364
[INFO] viewer: No OCP.Files app found, viewer is now in standalone mode 
Object { app: "viewer", uid: "christoph", level: 1 }
logger-CSHmak5d.chunk.mjs:5:299
[ERROR] viewer: Could not register handler 
Object { app: "viewer", uid: "christoph", level: 1, error: "The handler doesn't have a valid component", handler: {…} }
logger-CSHmak5d.chunk.mjs:5:434
    log index.mjs:54
    error index.mjs:72
    registerHandler Viewer.js:88
    <anonym> register-viewer.js:2
[INFO] viewer: 5 viewer handlers registered 
Object { app: "viewer", uid: "christoph", level: 1, handlers: (5) […] }
logger-CSHmak5d.chunk.mjs:5:299
[INFO] core: Clipboard API not available, using fallback core-main.js:1:443065
session heartbeat polling started core-main.js:1:422434
[INFO] comments: Comments plugin registered for Activity sidebar action 
Object { app: "comments", uid: "christoph", level: 1 }
core-common.js:1:2063431
[ERROR] photos: Error fetching files 
Object { app: "photos", uid: "christoph", level: 1, error: TypeError }
photos-main.js:1:10438
    value ConsoleLogger.js:74
    value ConsoleLogger.js:100
    fetchFiles FetchFilesMixin.js:109
    getContent Timeline.vue:263
    VueJS 4
    needContent FilesListViewer.vue:229
    VueJS 4
    isNearBottom VirtualScrolling.vue:259
    VueJS 12
    resizeObserver VirtualScrolling.vue:296
    (Async: ResizeObserverCallback)
    mounted VirtualScrolling.vue:293
    VueJS 18
    init vue-router.esm.js:3005
    init vue-router.esm.js:3004
[ERROR] photos: Error fetching files 
Object { app: "photos", uid: "christoph", level: 1, error: TypeError }
photos-main.js:1:10438
Notifications permissions denied NotificationsApp-w_eKRGrb.chunk.mjs:49:61045
Polling interval updated to 30000 NotificationsApp-w_eKRGrb.chunk.mjs:49:60340
Started background fetcher as session_keepalive is enabled NotificationsApp-w_eKRGrb.chunk.mjs:49:57544
Got notification data, restoring default polling interval. NotificationsApp-w_eKRGrb.chunk.mjs:49:59295

```
